### ISSUE TITLE
Readme documentation is lacking on concrete steps

### ISSUE THREAD

**Issue by Wandering-Consciousness** [smartcatai/smartcat-serge-sync-plugin#16]

**Comment by iafan** [comment]
I understand documentation is never enough, and we're woking on improving the existing one and will be adding more, but can you please elaborate on what exactly you have found missing as you were going through the installation or the linked Getting Started guide?

**Comment by Wandering-Consciousness** [comment]
I found them here: https://help.smartcat.ai/hc/en-us/articles/360029203972-Serge-Smartcat
