### ISSUE TITLE
Error while pushing to Smartcat Api.

### ISSUE THREAD

**Issue by zhukic** [smartcatai/smartcat-serge-sync-plugin#4]
Hi. When executing ```serge push-ts congig.serge``` command, I get an 400 error with message:
API Exception(400): Bad Request "Error processing request. Disassemble method 'Serge.io PO' is obsolete or not set up in account." at /usr/local/share/perl/5.26.1/Smartcat/App/Command/push.pm line 251.
My translation service configuration:
```
ts
    {
        plugin                      Smartcat

        data
        {
            project_id              $project_id

            token_id                $token_id

            token                   $token

            pull {
                complete_projects                NO
                complete_documents               NO
            }

            debug                                YES
        }
    }
```
Any thoughts about that?

**Comment by ta2-1** [comment]
@zhukic it looks like you need to contact Smartcat support to enable serge.io PO support. You’ll need to provide email from your corporate account.

**Comment by zhukic** [comment]
@ta2-1 I've contaced Smartcat support and everything works at now.
Thanks a lot!
