### ISSUE TITLE
Issue with environment variable in config file.

### ISSUE THREAD

**Issue by zhukic** [smartcatai/smartcat-serge-sync-plugin#6]
Hi. 
When I run `serge push-ts config.serge` I get an error with message:

`
Use of uninitialized value in regexp compilation at /Users/user/perl5/perlbrew/perls/perl-5.28.1/lib/site_perl/5.28.1/Serge/Sync/Plugin/TranslationService/Smartcat.pm line 64.
Exception occurred while processing configuration file: Data validation failed for plugin 'Serge::Sync::Plugin::TranslationService::Smartcat': 'ts_file_path' parent directory, which is set to '%ENV:PROJECT_DIR%/src/ci/serge/po', does not point to a valid directory. Run 'localize' to generate translation files. at /Users/user/perl5/perlbrew/perls/perl-5.28.1/lib/site_perl/5.28.1/Serge/Sync/Plugin/TranslationService/Smartcat.pm line 76.
`

My Serge config file:
```
sync
{
    ts
    {
        plugin                      Smartcat

        data
        {
            project_id              %ENV:SERGE_PROJECT_ID%

            token_id                %ENV:SERGE_TOKEN_ID%

            token                   %ENV:SERGE_TOKEN%
        }
    }
}

jobs
{
    {
        id                          localize_android_strings

        source_dir                  %ENV:PROJECT_DIR%/app/src/main/res/values
        source_process_subdirs      NO
        source_match                ^strings.xml$

        debug                       YES

        parser
        {
            plugin                  parse_android
        }

        db_namespace                android_project

        ts_file_path                %ENV:PROJECT_DIR%/po/%LANG%/%FILE%.po
        output_file_path            %ENV:PROJECT_DIR%/app/src/main/res/values-%LOCALE:ANDROID%/%NAME%.%EXT%

        source_language             en
        destination_languages       ru de es fr it

        db_source                   DBI:SQLite:dbname=%ENV:PROJECT_DIR%/translate.db3
    }

}
```
`serge localize` command works correctly.
Do you support environment variables in config file?

**Comment by iafan** [comment]
I recommend explicitly setting the path to the project files with the recently added `project_translation_files_path` parameter: https://github.com/smartcatai/smartcat-serge-sync-plugin/blob/master/lib/Serge/Sync/Plugin/TranslationService/Smartcat.pm#L29

The `project_translation_files_path` parameter supports `%ENV:...%` macros.

**Comment by zhukic** [comment]
It works, thanks. 
Also, would be great to add `project_translation_files_path` parameter into [README](https://github.com/smartcatai/smartcat-serge-sync-plugin/blob/master/README.md) file.

Thanks for help.
